### ISSUE TITLE
QDH Pilot Rollout Issues

### ISSUE THREAD

**Issue by shpurawat** [words-sdsc/QDH-Pilot-Release#1]

**Comment by zuojulia** [comment]
Hi all, 

Thanks for showing us the new pilot, it looks great so far! I have a few questions about the Jupyter notebook integration into the database and some other general things.

1. When I try to start the notebook server like Luke did in his demo, I get an error: 

> 500 : Internal Server Error
> Error in Authenticator.pre_spawn_start: KeyError "getpwnam(): name not found: 'jlzuo_umail_ucsb.edu'"

2. Can I upload a python library I've written myself to the server and use it (presumably with the upload feature Luke demoed)

3. My intern Kailey will hopefully be helping me digitize my data within this system. Can she and I have joint access to samples and their associated data structures at the moment?

Thanks,
Julia

**Comment by lukebrb** [comment]
Hi Julia! Sorry for not getting back to you sooner, just wrapped up my last midterm today.

1. ~~I have an idea of what could be causing this — I'll fix that asap.~~
2. That's a pretty great idea, I'll see if I can roll this into the library.
3. For now, _kinda_, since there isn't really a formal permissions/sharing system in this build. (Everything is "global" at the moment)

I'll be sure to update this thread with progress on these points as they get done. As always, feel free to comment on this thread (or create a new GitHub issue) if you have any other issues or suggestions!

Thanks!
-Luke

Update 11/6: Issue 1 is fixed in the latest patch. I'll be rolling it out tonight!

**Comment by zuojulia** [comment]
Hey all,

I'm still getting the same issue with the server that I was before (although it's definitely working for other people): Error in Authenticator.pre_spawn_start: KeyError "getpwnam(): name not found: 'jlzuo_umail_ucsb.edu'"

I actually just tried this on Edge instead of Chrome for my browser and I can get the server to start on Edge. Thought it might be an issue with an ad blocker at first but even after I turned it off, then uninstalled it, it won't work on Chrome.

Best,
Julia

**Comment by lukebrb** [comment]
Hi Julia, you'll need to clear your cookies for it to work in Chrome since your session data from the old version might still be there (this is just a one-time thing due to the nature of the bug that was fixed). While on QuantumDataHub, click the padlock icon on the left side of Chrome's URL bar, then "site settings", and then "clear data". 

Please let me know if this doesn't fix it, thank you!

**Comment by zuojulia** [comment]
Hey Luke,

I went back in to try this out again today and now have a completely different problem, on all browsers I've tried. Here's what I get when I try to use the jupyter notebook:
![11111](https://user-images.githubusercontent.com/73366996/99726112-edd52180-2a6a-11eb-8ffd-e9b78accbde7.PNG)

**Comment by lukebrb** [comment]
Gotcha, I think I found the issue — give it a shot again?

**Comment by zuojulia** [comment]
Success! Thanks Luke!

**Comment by stevenjgomez** [comment]
Hi all,

I just started using the data hub today and I guess the "New Sample" button is showing up halfway down the sample list, see below.

![Screenshot (94)](https://user-images.githubusercontent.com/72895195/99766618-4e3d8080-2ab6-11eb-834e-292e844a078c.png)

**Comment by lukebrb** [comment]
Hi @stevenjgomez ! Yep, definitely looks like the sidebar will be needing a redesign to better scale to the sheer number of samples. I'll push the button layout fixes Saturday evening, and in the near future I'll be adding folders and a search field to the sidebar.

Thanks for your patience!
